version: '3.9'

services:
  node:
    build: ./docker/node
    volumes:
      - ./node:/usr/src/app:cached
    working_dir: /usr/src/app/react-sample
    command: sh -c "npm start"
    ports:
      - "3000:3000"
